processors:
  active: true
  exclude:
    - 'DetektProgressListener'
#    - 'FunctionCountProcessor'
#    - 'PropertyCountProcessor'
#    - 'ClassCountProcessor'
#    - 'PackageCountProcessor'
#    - 'KtFileCountProcessor'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    #     - 'FindingsReport'
    - 'FileBasedFindingsReport'
